name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '1.0.0'
  pull_request:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.8'
      - name: Install matplotlib
        run: pip install matplotlib
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg;
                                       Pkg.add(url="https://github.com/grizzuti/AbstractLinearOperators.git");
                                       Pkg.add(PackageSpec(path=pwd()));
                                       Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          # DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ docs/make.jl